DB_USERNAME: root
DB_PASSWORD: root
DB_NAME: test_db
DB_URL: localhost

spring:
  liquibase:
    enabled: true
    change-log: classpath:config/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true